noWander = true
fairBreeds = true
portalPatch = true
rubberBand = true
breakSpeed = true
stepHeight = false
horseHeadAngleOffset = 0
jeb_Horses = true

[pitchFade]
enabled = true
startAngle = 30
endAngle = 50
maxTransparency = 90
