# The configuration file for Log Begone

[logbegone]
# If a log message has one of these phrases, it will be filtered out from logging
phrases = ["Disconnecting VANILLA connection attempt", "Channels ", "STDERR", "Ignoring chunk since it's not in the view range", "Trying to mark a block for PostProcessing", "########## GL ERROR ##########", "@ Pre render", "65539: Invalid key -1"]

# If a log message matches one of these regex patterns, it will be filtered out from logging. EX: 
regex = ["Disconnecting VANILLA connection attempt", "Channels ", "STDERR", "Ignoring chunk since it's not in the view range", "Trying to mark a block for PostProcessing", "########## GL ERROR ##########", "@ Pre render", "65539: Invalid key -1"]