ADD_OUTPOST_LOOT = true
SHOW_TOOLTIPS = true
CHEESE_MAKING_DURATION = 600
MIN_GOAT_CHEESE = 1
MAX_GOAT_CHEESE = 3
HURT_ATTACKER_PROBABILITY = 0.15
HORN_LOSING_PROBABILITY = 0.01
HORN_DROPPING_PROBABILITY = 0.85
