[extractinatorConfig]
commonItemChance = 100.0
uncommonItemChance = 50.0
rareItemChance = 25.0
veryRareItemChance = 10.0
extremelyRareItemChance = 2.0
inputCooldown = 8
outputLootMultiplier = 1.0
enableReiPercent = false
maximumUsages = 0
extractinatorRecipe = "NONE"
[worldConfig]
generateSiltOre_v1 = true
siltVeinSize_v2 = 13
siltVeinsPerChunk_v2 = 9
siltMinSpawnHeight_v1 = -64
siltMaxSpawnHeight_v1 = 24
generateSlushOre_v1 = true
slushVeinSize_v1 = 13
slushVeinsPerChunk_v1 = 10
slushMinSpawnHeight_v1 = 25
slushMaxSpawnHeight_v1 = 48
