# Configure card package drop chances from mobs
mobDrops:
  # Chance that no package is dropped on kill
  noDropWeight: 9500

  # Chance that common package is dropped on kill
  commonDropWeight: 251

  # Chance that uncommon package is dropped on kill
  uncommonDropWeight: 126

  # Chance that rare package is dropped on kill
  rareDropWeight: 64

  # Chance that epic package is dropped on kill
  epicDropWeight: 33

  # Chance that legendary package is dropped on kill
  legendaryDropWeight: 17

  # Chance that mythical package is dropped on kill
  mythicalDropWeight: 9

# Keep album in inventory through death
persistAlbumThroughDeath: false

# When set to true no cards will be received from package unless you flip all cards
requireTurnAllCards: false

