# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.doom]
				bfg_cell = true
				pinky = true
				gladiator = true
				shotgun_shell = true
				bullets = true

			[light_sources.settings.entities.biomemakeover]
				owl = true

			[light_sources.settings.entities.myloot]
				loot_chest_minecart = true

			[light_sources.settings.entities.galosphere]
				sparkle = true
				spectre = true
				silver_bomb = true

			[light_sources.settings.entities.impaled]
				elder_trident = true
				hellfork = true
				soulfork = true
				pitchfork = true
				atlan = true

			[light_sources.settings.entities.naturalist]
				deer = true
				rattlesnake = true
				zebra = true
				snail = true
				canary = true
				firefly = true
				rhino = true
				hippo = true
				bluejay = true
				coral_snake = true
				snake = true
				cardinal = true
				lion = true
				vulture = true
				robin = true
				boar = true
				butterfly = true
				giraffe = true
				bear = true
				elephant = true

			[light_sources.settings.entities.graveyard]
				acolyte = true
				revenant = true
				wraith = true
				corrupted_vindicator = true
				skeleton_creeper = true
				corrupted_pillager = true
				ghoul = true
				reaper = true
				nightmare = true

			[light_sources.settings.entities.pickyourpoison]
				poison_dart_frog = true

			[light_sources.settings.entities.aureate]
				mirror = true
				etherealwolf = true
				fire = true
				gauntlet = true
				galeswordproj = true

			[light_sources.settings.entities.doggomodoverhauled]
				tennis_ball_entity = true
				doggo = true

			[light_sources.settings.entities.immersive_aircraft]
				airship = true
				gyrodyne = true
				quadrocopter = true
				biplane = true

			[light_sources.settings.entities.adventurez]
				skeleton_vanguard = true
				deer = true
				thrown_rock = true
				desert_rhino = true
				small_stone_golem = true
				piglin_beast = true
				blaze_guardian = true
				ender_whale = true
				shaman = true
				dragon = true
				stone_golem = true
				iguana = true
				soul_reaper = true
				amethyst_golem = true
				red_fungus = true
				void_bullet = true
				summoner = true
				orc = true
				the_eye = true
				necromancer = true
				void_fragment = true
				brown_fungus = true
				blaze_guardian_shield = true
				nightmare = true
				mammoth = true
				void_shade = true
				enderwarthog = true
				void_shadow = true

			[light_sources.settings.entities.create]
				stationary_contraption = true
				contraption = true
				super_glue = true
				potato_projectile = true

			[light_sources.settings.entities.medievalweapons]
				netherite_javelin = true
				netherite_francisca = true
				pendorite_francisca = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.wildbackport]
				allay = true
				tadpole = true
				frog = true
				warden = true
				chest_boat = true

			[light_sources.settings.entities.bewitchment]
				leonard = true
				ghost = true
				werewolf = true
				owl = true
				vampire = true
				baphomet = true
				snake = true
				hellhound = true

			[light_sources.settings.entities.decorative_blocks]
				dummy = true

			[light_sources.settings.entities.mobscarecrow]
				cat_plushie = true
				steve_plushie = true
				wolf_plushie = true
				villager_plushie = true
				default_scarecrow = true
				zombie_plushie = true
				pillager_plushie = true

			[light_sources.settings.entities.musketmod]
				bullet = true

			[light_sources.settings.entities.vinery]
				mule = true
				wandering_winemaker = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.takesapillage]
				legioner = true
				archer = true
				skirmisher = true
				clay_golem = true

			[light_sources.settings.entities.bosses_of_mass_destruction]
				lich = true
				blue_fireball = true
				spore_ball = true
				petal_blade = true
				charged_ender_pearl = true
				comet = true
				gauntlet = true
				soul_star = true
				void_blossom = true

			[light_sources.settings.entities.immersive_portals]
				nether_portal_new = true
				loading_indicator = true

			[light_sources.settings.entities.pfm]
				chair = true

			[light_sources.settings.entities.arcanus]
				arcane_barrier = true
				magic_missile = true

			[light_sources.settings.entities.untitledduckmod]
				goose = true
				duck = true

			[light_sources.settings.entities.hwg]
				flare = true
				grenade = true
				blazerod = true
				rockets = true
				mbullets = true
				flame_firing = true
				technodemon_greater_1 = true
				shell = true
				technodemon_lesser_1 = true
				merc = true
				spy = true
				fireball = true
				bullets = true

			[light_sources.settings.entities.xercamusic]
				music_spirit = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true
				glare = true
				moobloom = true
				mauler = true
				iceologer = true

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				zoglin = true
				egg = true
				llama = true
				bat = true
				husk = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				mooshroom = true
				llama_spit = true
				glow_item_frame = false
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				endermite = true
				end_crystal = true
				zombie = true
				ender_pearl = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				small_fireball = true
				boat = true
				strider = true
				cave_spider = true
				witch = true
				cod = true
				snow_golem = true
				spider = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wither_skeleton = true
				vex = true
				wandering_trader = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				glow_squid = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.ants]
				red_ant = true
				brown_ant = true
				black_ant = true

			[light_sources.settings.entities.revamped_phantoms]
				shockwave = true

			[light_sources.settings.entities.ratsmischief]
				rat = true

			[light_sources.settings.entities.haema]
				vampirager = true
				vampire_hunter = true

			[light_sources.settings.entities.another_furniture]
				seat = true

			[light_sources.settings.entities.hookshot]
				hookshot = true

			[light_sources.settings.entities.capybara]
				capybara = true

			[light_sources.settings.entities.boatcontainer]
				furnace_boat = true
				chest_boat = true

			[light_sources.settings.entities.simplehats]
				hatdisplay = true

			[light_sources.settings.entities.gateofbabylon]
				spear = true
				yoyo = true
				boomerang = true

			[light_sources.settings.entities.crittersandcompanions]
				dragonfly = true
				leaf_insect = true
				koi_fish = true
				dumbo_octopus = true
				ferret = true
				otter = true
				red_panda = true
				sea_bunny = true

			[light_sources.settings.entities.xercapaint]
				easel = true

			[light_sources.settings.entities.mtmechs]
				magitekarmor = true

			[light_sources.settings.entities.varietyaquatic]
				shark = true
				hermitcrab = true
				jellyfish = true

			[light_sources.settings.entities.automobility]
				automobile = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.byg]
				boat = true

			[light_sources.settings.entities.the_bumblezone]
				honey_slime = true
				pollen_puff = true
				beehemoth = true

			[light_sources.settings.entities.conjuring]
				soul_projectile = true

			[light_sources.settings.entities.bouncylife]
				pet_slime = true

			[light_sources.settings.entities.smallships]
				brigg = true
				cog = true
				cannon_ball = true

			[light_sources.settings.entities.musketmodrevamped]
				bomb = true

			[light_sources.settings.entities.the_aether]
				aerbunny = true
				poison_needle = true
				aerwhale = true
				aechor_plant = true
				blue_swet = true

			[light_sources.settings.entities.earth]
				rubro = true
				carboranea = true
				pertilyo = true
				shimmer_shell = true

			[light_sources.settings.entities.exlinefurniture]
				entity_sit = true

			[light_sources.settings.entities.ad_astra]
				ice_spit_entity = true
				tier_2_rocket = true
				martian_raptor = true
				corrupted_lunarian = true
				lunarian = true
				tier_4_rocket = true
				tier_1_rover = true
				star_crawler = true
				lander = true
				glacian_ram = true

