SET_HEALTH = 1
REMOVE_ALL_EFFECTS = true
ENABLE_FIRE_RESISTANCE = true
FIRE_RESISTANCE_DURATION = 800
ENABLE_REGENERATION = true
REGENERATION_DURATION = 900
REGENERATION_AMPLIFIER = 1
ENABLE_ABSORPTION = true
ABSORPTION_DURATION = 100
ABSORPTION_AMPLIFIER = 1
USE_TOTEM_FROM_INVENTORY = false
APPLY_EFFECTS_ONLY_WHEN_NEEDED = true
ENABLE_WATER_BREATHING = true
WATER_BREATHING_DURATION = 800
ENABLE_SLOW_FALLING = true
SLOW_FALLING_DURATION = 600
ENABLE_INCREASE_FOOD_LEVEL = true
MINIMUM_FOOD_LEVEL = 6
SET_FOOD_LEVEL = 8
DESTROY_BLOCKS_WHEN_SUFFOCATING = true
DESTROY_POWDER_SNOW_WHEN_FULLY_FROZEN = true
KNOCKBACK_MOBS_AWAY = true
KNOCKBACK_RADIUS = 3.0
KNOCKBACK_STRENGTH = 2.5
TELEPORT_OUT_OF_VOID = true
TELEPORT_HEIGHT_OFFSET = 64
ADD_COOLDOWN = false
COOLDOWN = 200
USE_TOTEM_FROM_TRINKETS_SLOT = true
DISPLAY_TOTEM_ON_CHEST = true
BLACKLISTED_DIMENSIONS = []
BLACKLISTED_STRUCTURES = []
