#Hide enchantment glint when the item is solely enchanted with curses.
disguise_item = true
#Hide curse enchantments from the item tooltip.
hide_curses = true
#Cursed items have a red hover name instead of aqua.
color_item_name = true
#Hide curses from enchanted books if they also hold other enchantments.
affect_books = false
#Temporarily show tooltip as usual including curses while shift key is held.
shift_shows_curses = false

