keepHatOnDeath = false
allowUpdates = true
seasonalBagChance = 20
enableMobLoot = false
enableChestLoot = true
allowHatInHelmetSlot = false
chestNoneWeight = 150
chestCommonWeight = 20
chestUncommonWeight = 15
chestRareWeight = 10
chestEpicWeight = 5
entityNoneWeight = 200
entityCommonWeight = 20
entityUncommonWeight = 15
entityRareWeight = 10
entityEpicWeight = 5
